# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1500, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../../pysim/resources/stc_png.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(
            "\n" "background-color:rgba(32,33,36,255);\n" "color:white;\n" ""
        )
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(9, 9, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_8.setContentsMargins(15, -1, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_reader = QtWidgets.QGroupBox(parent=self.frame_2)
        self.groupBox_reader.setMaximumSize(QtCore.QSize(1200, 60))
        self.groupBox_reader.setTitle("")
        self.groupBox_reader.setObjectName("groupBox_reader")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_reader)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.reader_label = QtWidgets.QLabel(parent=self.groupBox_reader)
        self.reader_label.setMaximumSize(QtCore.QSize(74, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.reader_label.setFont(font)
        self.reader_label.setObjectName("reader_label")
        self.gridLayout_5.addWidget(self.reader_label, 0, 0, 1, 1)
        self.reader_refresh = QtWidgets.QPushButton(parent=self.groupBox_reader)
        self.reader_refresh.setMaximumSize(QtCore.QSize(50, 50))
        self.reader_refresh.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.reader_refresh.setStyleSheet(
            "#reader_refresh{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#reader_refresh:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.reader_refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("../resources/refresh.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.reader_refresh.setIcon(icon1)
        self.reader_refresh.setObjectName("reader_refresh")
        self.gridLayout_5.addWidget(self.reader_refresh, 0, 3, 1, 1)
        self.reader_comboBox = QtWidgets.QComboBox(parent=self.groupBox_reader)
        self.reader_comboBox.setMinimumSize(QtCore.QSize(500, 30))
        self.reader_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.reader_comboBox.setStyleSheet(
            "QComboBox#reader_comboBox{\n"
            "    border:                 none;\n"
            " background-color: rgba(63,64,66,255);\n"
            "color:                      white;\n"
            "    font-weight:            bold;\n"
            "    padding:                    5px;\n"
            "\n"
            "border:2px solid black;\n"
            "}\n"
            "QComboBox#reader_comboBox:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "\n"
            "}\n"
            "QListView{\n"
            "    border:                 none;\n"
            "    color:                     white;\n"
            "    background-color: rgba(63,64,66,255);\n"
            "    font-weight:            bold;\n"
            "    selection-background-color: rgb(0, 144, 196);\n"
            "    show-decoration-selected: 1;\n"
            "    margin-left:                -10px;\n"
            "    padding-left    :           15px;\n"
            "}\n"
            "QListView::item:hover{\n"
            "\n"
            "    background-color:   rgb(0, 144, 196);\n"
            "    border:                 none;\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.reader_comboBox.setObjectName("reader_comboBox")
        self.gridLayout_5.addWidget(self.reader_comboBox, 0, 1, 1, 1)
        self.reader_connection = QtWidgets.QPushButton(parent=self.groupBox_reader)
        self.reader_connection.setMinimumSize(QtCore.QSize(0, 25))
        self.reader_connection.setMaximumSize(QtCore.QSize(50, 50))
        self.reader_connection.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.reader_connection.setStyleSheet(
            "#reader_connection{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#reader_connection:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.reader_connection.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("../resources/connect.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.reader_connection.setIcon(icon2)
        self.reader_connection.setObjectName("reader_connection")
        self.gridLayout_5.addWidget(self.reader_connection, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_reader, 1, 0, 1, 1)
        self.groupBox_files = QtWidgets.QGroupBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.groupBox_files.sizePolicy().hasHeightForWidth()
        )
        self.groupBox_files.setSizePolicy(sizePolicy)
        self.groupBox_files.setMaximumSize(QtCore.QSize(1200, 250))
        self.groupBox_files.setTitle("")
        self.groupBox_files.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTrailing
        )
        self.groupBox_files.setObjectName("groupBox_files")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_files)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pre_os_check_box = QtWidgets.QCheckBox(parent=self.groupBox_files)
        self.pre_os_check_box.setText("")
        self.pre_os_check_box.setChecked(True)
        self.pre_os_check_box.setObjectName("pre_os_check_box")
        self.gridLayout_3.addWidget(self.pre_os_check_box, 0, 0, 1, 1)
        self.pre_os_path = QtWidgets.QLineEdit(parent=self.groupBox_files)
        self.pre_os_path.setMinimumSize(QtCore.QSize(0, 35))
        self.pre_os_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pre_os_path.setStyleSheet(
            "#pre_os_path{\n"
            "background-color: rgba(63,64,66,255);\n"
            "border-radius:5px;\n"
            "height:26px;\n"
            "border:2px solid black;\n"
            "padding-left:5px;\n"
            "}\n"
            "#pre_os_path:hover{\n"
            "border:2px solid black;\n"
            "}\n"
            ""
        )
        self.pre_os_path.setObjectName("pre_os_path")
        self.gridLayout_3.addWidget(self.pre_os_path, 0, 1, 1, 1)
        self.pre_os_browse_button = QtWidgets.QPushButton(parent=self.groupBox_files)
        self.pre_os_browse_button.setMinimumSize(QtCore.QSize(0, 25))
        self.pre_os_browse_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pre_os_browse_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.pre_os_browse_button.setStyleSheet(
            "#pre_os_browse_button{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#pre_os_browse_button:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.pre_os_browse_button.setObjectName("pre_os_browse_button")
        self.gridLayout_3.addWidget(self.pre_os_browse_button, 0, 2, 1, 1)
        self.os_sys_check_box = QtWidgets.QCheckBox(parent=self.groupBox_files)
        self.os_sys_check_box.setText("")
        self.os_sys_check_box.setChecked(True)
        self.os_sys_check_box.setObjectName("os_sys_check_box")
        self.gridLayout_3.addWidget(self.os_sys_check_box, 1, 0, 1, 1)
        self.op_sys_path = QtWidgets.QLineEdit(parent=self.groupBox_files)
        self.op_sys_path.setMinimumSize(QtCore.QSize(0, 35))
        self.op_sys_path.setStyleSheet(
            "#op_sys_path{\n"
            "background-color: rgba(63,64,66,255);\n"
            "border-radius:5px;\n"
            "height:26px;\n"
            "border:2px solid black;\n"
            "padding-left:5px;\n"
            "}\n"
            "#op_sys_path:hover{\n"
            "border:2px solid black;\n"
            "}\n"
            ""
        )
        self.op_sys_path.setObjectName("op_sys_path")
        self.gridLayout_3.addWidget(self.op_sys_path, 1, 1, 1, 1)
        self.op_sys_browse_button = QtWidgets.QPushButton(parent=self.groupBox_files)
        self.op_sys_browse_button.setMinimumSize(QtCore.QSize(0, 0))
        self.op_sys_browse_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.op_sys_browse_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.op_sys_browse_button.setStyleSheet(
            "#op_sys_browse_button{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#op_sys_browse_button:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.op_sys_browse_button.setObjectName("op_sys_browse_button")
        self.gridLayout_3.addWidget(self.op_sys_browse_button, 1, 2, 1, 1)
        self.pre_perso_check_box = QtWidgets.QCheckBox(parent=self.groupBox_files)
        self.pre_perso_check_box.setText("")
        self.pre_perso_check_box.setChecked(True)
        self.pre_perso_check_box.setObjectName("pre_perso_check_box")
        self.gridLayout_3.addWidget(self.pre_perso_check_box, 2, 0, 1, 1)
        self.pre_perso_path = QtWidgets.QLineEdit(parent=self.groupBox_files)
        self.pre_perso_path.setMinimumSize(QtCore.QSize(0, 35))
        self.pre_perso_path.setStyleSheet(
            "#pre_perso_path{\n"
            "background-color: rgba(63,64,66,255);\n"
            "border-radius:5px;\n"
            "height:26px;\n"
            "border:2px solid black;\n"
            "padding-left:5px;\n"
            "}\n"
            "#pre_perso_path:hover{\n"
            "border:2px solid black;\n"
            "}\n"
            ""
        )
        self.pre_perso_path.setObjectName("pre_perso_path")
        self.gridLayout_3.addWidget(self.pre_perso_path, 2, 1, 1, 1)
        self.pre_perso_browse_button = QtWidgets.QPushButton(parent=self.groupBox_files)
        self.pre_perso_browse_button.setMinimumSize(QtCore.QSize(0, 0))
        self.pre_perso_browse_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pre_perso_browse_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.pre_perso_browse_button.setStyleSheet(
            "#pre_perso_browse_button{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#pre_perso_browse_button:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.pre_perso_browse_button.setObjectName("pre_perso_browse_button")
        self.gridLayout_3.addWidget(self.pre_perso_browse_button, 2, 2, 1, 1)
        self.perso_check_box = QtWidgets.QCheckBox(parent=self.groupBox_files)
        self.perso_check_box.setText("")
        self.perso_check_box.setChecked(True)
        self.perso_check_box.setObjectName("perso_check_box")
        self.gridLayout_3.addWidget(self.perso_check_box, 3, 0, 1, 1)
        self.perso_path = QtWidgets.QLineEdit(parent=self.groupBox_files)
        self.perso_path.setMinimumSize(QtCore.QSize(0, 35))
        self.perso_path.setStyleSheet(
            "#perso_path{\n"
            "background-color: rgba(63,64,66,255);\n"
            "border-radius:5px;\n"
            "height:26px;\n"
            "border:2px solid black;\n"
            "padding-left:5px;\n"
            "}\n"
            "#perso_path:hover{\n"
            "border:2px solid black;\n"
            "}\n"
            ""
        )
        self.perso_path.setObjectName("perso_path")
        self.gridLayout_3.addWidget(self.perso_path, 3, 1, 1, 1)
        self.perso_browse_button = QtWidgets.QPushButton(parent=self.groupBox_files)
        self.perso_browse_button.setMinimumSize(QtCore.QSize(0, 0))
        self.perso_browse_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.perso_browse_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.perso_browse_button.setStyleSheet(
            "#perso_browse_button{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#perso_browse_button:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.perso_browse_button.setObjectName("perso_browse_button")
        self.gridLayout_3.addWidget(self.perso_browse_button, 3, 2, 1, 1)
        self.load_button = QtWidgets.QPushButton(parent=self.groupBox_files)
        self.load_button.setMinimumSize(QtCore.QSize(0, 0))
        self.load_button.setMaximumSize(QtCore.QSize(75, 35))
        self.load_button.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.load_button.setStyleSheet(
            "#load_button{background-color: rgba(63,64,66,255);\n"
            'font: 600 9pt "Segoe UI";\n'
            "height:26px;\n"
            "width:80px;\n"
            "border-radius:5px;\n"
            "border:2px solid black;\n"
            "}\n"
            "#load_button:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "}"
        )
        self.load_button.setObjectName("load_button")
        self.gridLayout_3.addWidget(self.load_button, 4, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_files, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8.addWidget(self.frame_4, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_3)
        self.textEdit.setStyleSheet(
            "QTextEdit{\n"
            "background-color: rgba(63,64,66,255);\n"
            'font: 550 9pt "Segoe UI";\n'
            "color:White;\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "}"
        )
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard
            | QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
            | QtCore.Qt.TextInteractionFlag.TextBrowserInteraction
            | QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard
            | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
        )
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.Contact_Reader_0 = QtGui.QAction(parent=MainWindow)
        self.Contact_Reader_0.setObjectName("Contact_Reader_0")
        self.Contactless_Reader_1 = QtGui.QAction(parent=MainWindow)
        self.Contactless_Reader_1.setObjectName("Contactless_Reader_1")
        self.Smart_Card_Reader_USB_0 = QtGui.QAction(parent=MainWindow)
        self.Smart_Card_Reader_USB_0.setObjectName("Smart_Card_Reader_USB_0")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reader_label.setText(_translate("MainWindow", "Select Reader"))
        self.pre_os_browse_button.setText(_translate("MainWindow", "BL/RESTORE"))
        self.op_sys_browse_button.setText(_translate("MainWindow", "OS"))
        self.pre_perso_browse_button.setText(_translate("MainWindow", "PRE-PERSO"))
        self.perso_browse_button.setText(_translate("MainWindow", "PERSO"))
        self.load_button.setText(_translate("MainWindow", "LOAD"))
        self.Contact_Reader_0.setText(
            _translate("MainWindow", "JAVACOS Virtual Contact Reader 0")
        )
        self.Contactless_Reader_1.setText(
            _translate("MainWindow", "JAVACOS Virtual Contactless Reader 1")
        )
        self.Smart_Card_Reader_USB_0.setText(
            _translate("MainWindow", "OMNIKEY Smart Card Reader USB 0")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
